import os
import sys
import signal
import subprocess
import threading
import time
import shutil

STATIC_FILE = "/tmp/swarm_telemetry.mov"

def handle_pipe(pipe_path, proc, log_file):
    try:
        with open(pipe_path, 'r') as fifo:
            if "STOP" in fifo.read().upper():
                log_file.write(f"Initiating graceful SIGINT shutdown via killall...\n")
                log_file.flush()
                subprocess.run(['killall', '-INT', 'screencapture'])
    except Exception as e:
        log_file.write(f"Pipe collapsed: {e}\n")

def main():
    if len(sys.argv) < 2:
        print("Usage: python shadow_telemetry.py /tmp/output.mov")
        sys.exit(1)
        
    output_file = sys.argv[1]
    pipe_path = output_file + ".pipe"
    log_path = output_file + ".log"
    
    applet_bin = os.path.join(os.path.dirname(os.path.abspath(__file__)), "SwarmTelemetry.app", "Contents", "MacOS", "applet")
    
    if os.path.exists(pipe_path): os.remove(pipe_path)
    os.mkfifo(pipe_path)
    
    # Pre-clean static target
    if os.path.exists(STATIC_FILE): os.remove(STATIC_FILE)
    
    with open(log_path, 'w') as log_file:
        proc = subprocess.Popen(
            [applet_bin],
            stdout=log_file, stderr=subprocess.STDOUT
        )
        
        threading.Thread(target=handle_pipe, args=(pipe_path, proc, log_file), daemon=True).start()
        
        proc.wait() # Blocking wait on main thread until the Subprocess signals closed.
        time.sleep(1) # Let the OS flush video buffers fully out of screencapture
        
        if os.path.exists(STATIC_FILE):
            shutil.move(STATIC_FILE, output_file)
            log_file.write(f"Moved {STATIC_FILE} to {output_file}\n")
        else:
            log_file.write(f"CRITICAL FAILURE: {STATIC_FILE} was not generated by SwarmTelemetry.app (TCC Sandbox blocked/Failed Execution)\n")
            
    if os.path.exists(pipe_path): os.remove(pipe_path)

if __name__ == "__main__":
    main()
